config/routes.rb
Rails.application.routes.draw do

  # 顧客用
  # URL /customers/sign_in ...
  devise_for :user, controllers: {
    registrations: "user/registrations",
    sessions: 'user/sessions'
  }

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, controllers: {
    sessions: "admin/sessions",
  }

  # ゲストログイン用
  # post '/homes/guest_sign_in' => 'homes#guest_sign_in'
  devise_scope :user do
    post 'user/guest_sign_in' => 'user/sessions#guest_sign_in'
  end

  root to: 'user/homes#top'

  scope module: :user do
    get 'homes/about'
    get 'feedbacks/thanks'
    resources:feedbacks, only: [:new, :create]
    get 'users/mypage/edit' => 'users#edit'
    patch 'users/mypage/edit' => 'users#update'
    get 'users/check'
    patch 'users/withdraw'
    resources:users, only: [:index, :show, :edit, :destroy]

    resources:breads, only: [:index, :new, :create, :show, :edit, :update, :destroy] do
      resources:comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
      collection do
        get 'search'
      end
    end

    get 'favorites/index'

    resources:topics, only: [:index, :show]
    get 'shops/onlines'

    resources:shops, only: [:index, :show] do
      collection do
        get 'search'
      end
    end

    get 'drinks/index'
  end

  namespace :admin do
    root to: 'homes#top'
    resources:users, only: [:index, :show, :edit, :update, :destroy]

    resources:breads, only: [:index, :show, :destroy] do
      resources:comments, only: [:create, :destroy]
      collection do
        get 'search'
      end
    end

    resources:topics, only: [:index, :new, :create, :show, :edit, :update, :destroy]
    resources:shops, only: [:index, :new, :create, :show, :edit, :update, :destroy]
    resources:drinks, only: [:index, :new, :create, :edit, :update, :destroy]
    get 'feedbacks/solved'    # 解決済みご意見のindex
    resources:feedbacks, only: [:index, :show, :update, :destroy]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/topic.rb
class Topic < ApplicationRecord
  belongs_to :bread, optional: true    #breadモデルはお互い0以上でもOK
  has_many :shop_topics

  validates :title, presence: true, length:{maximum:30}
  validates :body, presence: true

  has_one_attached :bread_image

  def get_bread_image(width, height)
    unless bread_image.attached?
      file_path = Rails.root.join('app/assets/images/about_image640.jpg')
      bread_image.attach(io: File.open(file_path), filename: "default-image.jpg", content_type: "image/jpeg")
    end
    bread_image.variant(resize_to_fill: [width, height]).processed   #写真をresize_to_fillでスクエアに
  end

end

app/controllers/admin/topics_controller.rb
class Admin::TopicsController < ApplicationController
  before_action :authenticate_admin!

  def new
    @topic = Topic.new
  end

  def create
    @topic = Topic.new(topic_params)
    if @topic.save
      flash[:notice] = "特集の登録が完了しました"
      redirect_to admin_topic_path(@topic.id)
    else
      render :new
    end
  end

  def index
    @topics = Topic.all.order(created_at: :desc).page(params[:page]).per(20)
  end

  def show
    @topic = Topic.find(params[:id])
  end

  def edit
    @topic = Topic.find(params[:id])
  end

  def update
    @topic = Topic.find(params[:id])
    if @topic.update(topic_params)
      flash[:notice] = "特集を更新しました"
      redirect_to admin_topic_path(@topic.id)
    else
      render :edit
    end
  end

  def destroy
    @topic = Topic.find(params[:id])
    if @topic.delete
      flash[:notice] = "特集を削除しました"
      redirect_to admin_topics_path
    end
  end

  private
  def topic_params
    params.require(:topic).permit(:title, :body, :bread_image, :is_published)
  end
end

app/controllers/user/topics_controller.rb
class User::TopicsController < ApplicationController
  def index
    @topics = Topic.all.order(created_at: :desc).page(params[:page]).per(10)
  end

  def show
    @topic = Topic.find(params[:id])
  end
end

app/helpers/admin/topics_helper.rb
module Admin::TopicsHelper
end

app/helpers/user/topics_helper.rb
module User::TopicsHelper
end

app/views/admin/topics/destroy.html.erb
<h1>Admin::Topics#destroy</h1>
<p>Find me in app/views/admin/topics/destroy.html.erb</p>

app/views/admin/topics/edit.html.erb
<div class="main-theme container py-5">
  <div class="col-md-8 mx-auto">

    <h5 class="mb-4">特集を編集する</h5>

    <%= render 'layouts/errors', obj: @topic %>

    <%= form_with model: @topic, url: admin_topic_path do |f| %>
      <%= f.label :タイトル %><br>
      <%= f.text_field :title, class:'form-control', placeholder: "*25文字以内" %><br>
      <%= f.label :本文 %><br>
      <%= f.text_area :body, rows: 16, class:'form-control' %><br>

      <%= f.file_field :bread_image %><br>

      <%= f.submit "特集を更新する", class:"btn btn-danger mt-3" %>
    <% end %>
    <p><%= link_to "特集一覧ページ", admin_topics_path, class:"mt-5 btn btn-sm btn-outline-secondary" %></p>

  </div>
</div>

app/views/admin/topics/index.html.erb
<div class="main-theme container py-5">
  <div class="col-md-12 mx-auto">

    <% if flash[:notice] %>
      <div class="alert alert-secondary" role="alert">
        <%= flash[:notice] %>
      </div>
    <% end %>

    <div class="row">
      <div class="col-md-12 mx-auto">
        <h5>特集一覧</h5>
        <p><%= link_to "特集新規登録", new_admin_topic_path, class:"btn btn-sm btn-secondary mt-2" %></p>
      </div>
    </div>

    <div class="row">
      <div class="col-md-10">
        <% @topics.each do |topic| %>
          <%= link_to admin_topic_path(topic.id), class:"text-dark" do %>
          <div style="background-color: white;" class="p-3 mb-3">
            <h5><span class="mr-2" style="font-size: 15px">No.<%= topic.id %></span><%= topic.title %></h5>
            <p style="max-width: auto;" class="sentence"><%= topic.body %></p>
            <p>
              作成日: <%= topic.created_at.strftime('%Y/%m/%d') %>
              <% if topic.is_published == false %>
                <span class="text-secondary ml-2">非公開</span>
              <% else %>
                <span class="text-success ml-2">公開中</span>
              <% end %>
            </p>
          </div>
          <% end %>
        <% end %>

        <div class="d-flex justify-content-center">
          <%= paginate @topics, theme: 'twitter-bootstrap-4' %>
        </div>

      </div>
    </div>

  </div>
</div>

app/views/admin/topics/new.html.erb
<div class="main-theme container py-5">
  <div class="col-md-8 mx-auto">

    <h5 class="mb-4">特集新規登録</h5>

    <%= render 'layouts/errors', obj: @topic %>

    <%= form_with model: @topic, url:admin_topics_path do |f| %>
      <%= f.label :タイトル %><br>
      <%= f.text_field :title, class:'form-control', placeholder: "*25文字以内" %><br>
      <%= f.label :本文 %><br>
      <%= f.text_area :body, rows: 16, class:'form-control' %><br>

      <%= f.file_field :bread_image %><br>

      <%= f.submit "特集を保存する", class:"btn btn-secondary mt-3" %>
    <% end %>

    <p><%= link_to "特集一覧ページ", admin_topics_path, class:"mt-5 btn btn-sm btn-outline-secondary" %></p>

  </div>
</div>

app/views/admin/topics/show.html.erb
<div class="main-theme container py-5">

  <% if flash[:notice] %>
    <div class="alert alert-success" role="alert">
      <%= flash[:notice] %>
    </div>
  <% end %>

  <div class="col-md-8 col-sm-10 mx-auto">
    <h4 class="mb-3"><%= @topic.title %></h4>
    <div style="word-wrap: break-word;">
      <%=safe_join(@topic.body.split("\n"),tag(:br))%> <!--改行表示-->
    </div>
    <%= image_tag @topic.get_bread_image(400, 300), class:"mt-4 mx-auto d-block resize-image" %>
    <div class="mt-5">
      <span><%= link_to "特集一覧ページ", admin_topics_path, class:"btn btn-sm btn-warning" %></span>
      <span><%= link_to "編集", edit_admin_topic_path(@topic.id), class:"ml-5 btn btn-sm btn-outline-secondary" %></span>
      <span><%= link_to "削除", admin_topic_path(@topic.id), method: :delete, "data-confirm" => "本当に削除しますか？", class:"ml-2 btn btn-sm btn-outline-danger" %></span>
    </div>

    <div>
      <p class="mt-4">
        <% if @topic.is_published == false %>
          現在の公開状況：<span class="text-secondary pl-2">非公開</span>
        <% else %>
          現在の公開状況：<span class="text-success pl-2">公開中</span>
        <% end %>
      </p>
      <%= form_with model: @topic, url:admin_topic_path, method: :patch do |f| %>
        <div>
          <% if @topic.is_published == false %>
            <%= f.radio_button :is_published, :false, checked: true %>
             非公開
            <%= f.radio_button :is_published, :true, class:'ml-4' %>
             公開中
          <% else %>
            <%= f.radio_button :is_published, :false, checked: true %>
             非公開
            <%= f.radio_button :is_published, :true, class:"ml-4" %>
             公開中
          <% end %>
          </div>
        <%= f.submit '公開状況を変更する', "data-confirm" => "公開状況を変更します", class: 'mt-1 btn btn-danger btn-sm' %>
      <% end %>
    </div>

  </div>
</div>