config/routes.rb
Rails.application.routes.draw do

  # 顧客用
  # URL /customers/sign_in ...
  devise_for :user, controllers: {
    registrations: "user/registrations",
    sessions: 'user/sessions'
  }

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, controllers: {
    sessions: "admin/sessions",
  }

  # ゲストログイン用
  # post '/homes/guest_sign_in' => 'homes#guest_sign_in'
  devise_scope :user do
    post 'user/guest_sign_in' => 'user/sessions#guest_sign_in'
  end

  root to: 'user/homes#top'

  scope module: :user do
    get 'homes/about'
    get 'feedbacks/thanks'
    resources:feedbacks, only: [:new, :create]
    get 'users/mypage/edit' => 'users#edit'
    patch 'users/mypage/edit' => 'users#update'
    get 'users/check'
    patch 'users/withdraw'
    resources:users, only: [:index, :show, :edit, :destroy]

    resources:breads, only: [:index, :new, :create, :show, :edit, :update, :destroy] do
      resources:comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
      collection do
        get 'search'
      end
    end

    get 'favorites/index'

    resources:topics, only: [:index, :show]
    get 'shops/onlines'

    resources:shops, only: [:index, :show] do
      collection do
        get 'search'
      end
    end

    get 'drinks/index'
  end

  namespace :admin do
    root to: 'homes#top'
    resources:users, only: [:index, :show, :edit, :update, :destroy]

    resources:breads, only: [:index, :show, :destroy] do
      resources:comments, only: [:create, :destroy]
      collection do
        get 'search'
      end
    end

    resources:topics, only: [:index, :new, :create, :show, :edit, :update, :destroy]
    resources:shops, only: [:index, :new, :create, :show, :edit, :update, :destroy]
    resources:drinks, only: [:index, :new, :create, :edit, :update, :destroy]
    get 'feedbacks/solved'    # 解決済みご意見のindex
    resources:feedbacks, only: [:index, :show, :update, :destroy]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!

  def top
    @breads = Bread.active_users_breads.all.order(created_at: :desc).limit(30)
    @active_users = User.where(is_delete: false)  # 有効ユーザー数
    @feedbacks = Feedback.all.order(created_at: :desc).limit(5)
  end
end

app/controllers/user/homes_controller.rb
class User::HomesController < ApplicationController
  def top
    @breads = Bread.active_users_breads.all.order(created_at: :desc).page(params[:page]).per(20)
    @sweet_breads = @breads.where(taste: true).page(params[:page]).per(20)
    @salty_breads = @breads.where(taste: false).page(params[:page]).per(20)

    # 過去一週間のいいね順
    to = Time.current.at_end_of_day
    from = (to - 6.day).at_beginning_of_day
    @favorite_breads = Bread.active_users_breads.includes(:favorited_users)
      .sort_by {|x|
        x.favorited_users.includes(:favorites).where(created_at: from...to).size
      }.reverse
    # いいね順のページネーション記述
    @favorite_breads = Kaminari.paginate_array(@favorite_breads).page(params[:page]).per(20)

    # views/layouts/_side.html.erbに必要な記述
    @shops = Shop.all.order(created_at: :desc)
    @topics = Topic.all.order(created_at: :desc)
    @default_drinks = Drink.default.where(default_select: true)
  end


end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/user/homes_helper.rb
module User::HomesHelper
end

app/views/admin/homes/top.html.erb
<!--管理者トップ-->
<div class="main-theme container py-5">

  <div class="row">
    <div class="col-md-7">
      <div class="mb-4 p-3 bg-white">
        <%= link_to admin_users_path do %>
          <span class="text-dark">現在の有効ユーザー：　<%= @active_users.count %> users</span><br>
        <% end %>
        <%= link_to admin_breads_path do %>
          <span class="text-dark">現在の投稿パン：　<%= @breads.count %> posts</span>
        <% end %>
      </div>
    </div>
  </div>

  <h5><%= link_to "ご意見一覧 >", admin_feedbacks_path %></h5>

  <div class="row col-md-12 mx-auto p-3 bg-white">
    <% if @feedbacks.exists? %>
      <% @feedbacks.each do |feedback| %>
        <% if feedback.is_solved == false %>
          <table class="table">
            <tr>
              <td>No.<%= feedback.id %></td>
              <td class="sentence", style="max-width: 100px;">
                <%= link_to admin_feedback_path(feedback.id) do %>
                  <%= feedback.opinion %>
                <% end %>
              </td>
              <td>
                <span class="text-secondary mr-3 small">
                  <%= link_to admin_user_path(feedback.user.id) do %>
                    <%= feedback.user.name %><br>
                  <% end %>
                  <%= feedback.created_at.in_time_zone('Tokyo').strftime("%Y/%m/%d %H:%M") %>
                </span>
              </td>
            </tr>
          </table>
        <% end %>
      <% end %>
    <% end %>
  </div>

  <h5 class="ml-1 mt-4"><%= link_to "投稿一覧 >", admin_breads_path %></h5>
  <ul class="row col-md-12 mx-auto">
    <% @breads.each_with_index do |bread| %>
      <li class="mr-1 sentence" style="max-width: 100px;">
        <%= link_to admin_bread_path(bread.id) do %>
          <%= image_tag bread.get_bread_image(100, 100) %>
          <p class="text-dark"><%= bread.bread_name %></p>
        <% end %>
      </li>
    <% end %>
  </ul>

</div>