config/routes.rb
Rails.application.routes.draw do

  # 顧客用
  # URL /customers/sign_in ...
  devise_for :user, controllers: {
    registrations: "user/registrations",
    sessions: 'user/sessions'
  }

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, controllers: {
    sessions: "admin/sessions",
  }

  # ゲストログイン用
  # post '/homes/guest_sign_in' => 'homes#guest_sign_in'
  devise_scope :user do
    post 'user/guest_sign_in' => 'user/sessions#guest_sign_in'
  end

  root to: 'user/homes#top'

  scope module: :user do
    get 'homes/about'
    get 'feedbacks/thanks'
    resources:feedbacks, only: [:new, :create]
    get 'users/mypage/edit' => 'users#edit'
    patch 'users/mypage/edit' => 'users#update'
    get 'users/check'
    patch 'users/withdraw'
    resources:users, only: [:index, :show, :edit, :destroy]

    resources:breads, only: [:index, :new, :create, :show, :edit, :update, :destroy] do
      resources:comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
      collection do
        get 'search'
      end
    end

    get 'favorites/index'

    resources:topics, only: [:index, :show]
    get 'shops/onlines'

    resources:shops, only: [:index, :show] do
      collection do
        get 'search'
      end
    end

    get 'drinks/index'
  end

  namespace :admin do
    root to: 'homes#top'
    resources:users, only: [:index, :show, :edit, :update, :destroy]

    resources:breads, only: [:index, :show, :destroy] do
      resources:comments, only: [:create, :destroy]
      collection do
        get 'search'
      end
    end

    resources:topics, only: [:index, :new, :create, :show, :edit, :update, :destroy]
    resources:shops, only: [:index, :new, :create, :show, :edit, :update, :destroy]
    resources:drinks, only: [:index, :new, :create, :edit, :update, :destroy]
    get 'feedbacks/solved'    # 解決済みご意見のindex
    resources:feedbacks, only: [:index, :show, :update, :destroy]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/admin/breads_controller.rb
class Admin::BreadsController < ApplicationController
  before_action :authenticate_admin!

  def search
    if params[:keyword].present?
      @search_breads = Bread.active_users_breads.where('bread_name LIKE ?', "%#{params[:keyword]}%").page(params[:page]).per(100)
      @keyword = params[:keyword]
      @shops = Shop.all.order(created_at: :desc)
    else
      redirect_to root_path    # 検索窓が空白の場合root_pathに遷移
    end
  end


  def index
    @breads = Bread.active_users_breads.all.order(updated_at: :desc).page(params[:page]).per(100)
  end

  def show
    @bread = Bread.find(params[:id])
    @user = @bread.user
  end

  def destroy
    bread = Bread.find(params[:id])
    user_id = bread.user.id

    bread.destroy
    redirect_to admin_user_path(user_id)

  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @users = User.all.order(created_at: :desc).page(params[:page]).per(20)
  end

  def show
    @user = User.find(params[:id])
    @breads = @user.breads.all.order(updated_at: :desc).page(params[:page]).per(50)  # 更新日順に
  end

  def edit
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "変更を保存しました"
      redirect_to admin_user_path(@user.id)
    else
      redirect_to request.referer
    end
  end

  def destroy
  end

  private
  def user_params
    params.require(:user).permit(:is_delete)
  end

end

app/controllers/user/breads_controller.rb
class User::BreadsController < ApplicationController
  before_action :authenticate_user!, except: %i[search index show]

  def search
    if params[:keyword].present?
      @search_breads = Bread.active_users_breads.where('bread_name LIKE ?', "%#{params[:keyword]}%").page(params[:page]).per(20)
      @keyword = params[:keyword]
    else
      redirect_to root_path    # 検索窓が空白の場合root_pathに遷移
    end
  end

  def index
    return redirect_to root_path unless params[:drink_id]    # breads/new再リロード時のエラー回避
    @drink = Drink.find_by(id: params[:drink_id])
    @breads = @drink.breads.active_users_breads.order(created_at: :desc).page(params[:page]).per(20)
  end

  def show
    # 例外処理、削除された投稿はアクセス不可
    begin
      @bread = Bread.find(params[:id])
      @user = @bread.user
      @comment = Comment.new
    rescue ActiveRecord::RecordNotFound
      redirect_to root_path
    end
  end

  def new
    @bread = Bread.new
  end

  def create
    @bread = Bread.new(bread_params)
    @bread.user_id = current_user.id

    if params[:bread][:drink_name] == "other"
      drink_id = params[:bread][:other_drink_name]
    else
      drink_id = params[:bread][:drink_name]
    end

    drink = Drink.find_by(id: drink_id)
    @bread.drink_id = drink.id

    unless @bread.save
      render "user/breads/error.js.erb"
    else
      redirect_to bread_path(@bread.id)
    end
  end

  def edit
    @bread = Bread.find(params[:id])
  end

  def update
    @bread = Bread.find(params[:id])

    if params[:bread][:drink_name] == "other"
      drink_id = params[:bread][:other_drink_name]
    else
      drink_id = params[:bread][:drink_name]
    end

    drink = Drink.find(drink_id)

    @bread.drink = drink

    unless @bread.update(bread_params)
      render 'user/breads/error.js.erb'
    else
      flash[:notice] = "投稿を編集しました"
      redirect_to bread_path
    end
  end

  def destroy
    bread = Bread.find(params[:id])
    bread.destroy
    redirect_to user_path(current_user)
  end


  private
  def bread_params
    params.require(:bread).permit(:bread_name, :introduce, :taste, :bread_image, :shop_id, drink_attributes: [:drink_name, :other_drink_name])
  end


end

app/controllers/user/comments_controller.rb
class User::CommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    @bread = Bread.find(params[:bread_id])
    comment = current_user.comments.new(comment_params)
    comment.save
  end

  def destroy
    Comment.find(params[:id]).destroy
    @bread = Bread.find(params[:bread_id])
  end

  private
  def comment_params
    params.require(:comment).permit(:comment).merge(bread_id: params[:bread_id])
  end
end

app/controllers/user/confirmations_controller.rb
# frozen_string_literal: true

class User::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/user/drinks_controller.rb
class User::DrinksController < ApplicationController
  def index
  end
end

app/controllers/user/favorites_controller.rb
class User::FavoritesController < ApplicationController
  before_action :authenticate_user!

  def create
    @bread = Bread.find(params[:bread_id])
    favorite = current_user.favorites.new(bread_id: @bread.id)
    favorite.save
    # redirect_to bread_path(bread.id)
  end

  def destroy
    @bread = Bread.find(params[:bread_id])
    favorite = current_user.favorites.find_by(bread_id: @bread.id)
    favorite.destroy
    # redirect_to bread_path(bread.id)
  end

  def index
    @favorites = current_user.favorites.includes(:bread).page(params[:page]).per(50)
    # current_userの、Breadモデルのデータを含むfavorites(つまりいいね)を取得する。
  end
end

app/controllers/user/feedbacks_controller.rb
class User::FeedbacksController < ApplicationController
  before_action :authenticate_user!

  def new
    @feedback = Feedback.new
  end

  def create
    @feedback = Feedback.new(feedback_params)
    @feedback.user = current_user

    if @feedback.save!
      redirect_to feedbacks_thanks_path
    else
      render :new
    end
  end


  private
  def feedback_params
    params.require(:feedback).permit(:opinion, :is_solved)
  end

end

app/controllers/user/homes_controller.rb
class User::HomesController < ApplicationController
  def top
    @breads = Bread.active_users_breads.all.order(created_at: :desc).page(params[:page]).per(20)
    @sweet_breads = @breads.where(taste: true).page(params[:page]).per(20)
    @salty_breads = @breads.where(taste: false).page(params[:page]).per(20)

    # 過去一週間のいいね順
    to = Time.current.at_end_of_day
    from = (to - 6.day).at_beginning_of_day
    @favorite_breads = Bread.active_users_breads.includes(:favorited_users)
      .sort_by {|x|
        x.favorited_users.includes(:favorites).where(created_at: from...to).size
      }.reverse
    # いいね順のページネーション記述
    @favorite_breads = Kaminari.paginate_array(@favorite_breads).page(params[:page]).per(20)

    # views/layouts/_side.html.erbに必要な記述
    @shops = Shop.all.order(created_at: :desc)
    @topics = Topic.all.order(created_at: :desc)
    @default_drinks = Drink.default.where(default_select: true)
  end


end

app/controllers/user/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class User::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/user/passwords_controller.rb
# frozen_string_literal: true

class User::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/user/registrations_controller.rb
# frozen_string_literal: true

class User::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  def update_resource(resource, params)
    resource.update_without_current_password(params)
  end

  def after_update_path_for(resource)
    user_path(@user.id)
  end


  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/user/sessions_controller.rb
# frozen_string_literal: true

class User::SessionsController < Devise::SessionsController
  before_action :user_state, only: [:create]


  def guest_sign_in
    # user = User.find_or_create_by!(email: 'guest@example.com') do |user|
    user = User.guest
    sign_in user
    redirect_to root_path
  end

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end


  protected
  # 退会しているかを判断するメソッド
  def user_state
    @user = User.find_by(email: params[:user][:email])

    return if !@user  #@userが取得できなかった場合はそこで終了(returnで切る)
    if @user.valid_password?(params[:user][:password]) && @user.is_delete   #@userが取得できた場合、passwordが取得したemailのアカウントと一致しているかか確認
      flash[:alert] = "退会済みです"
      redirect_to new_user_registration_path
    end
  end




  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/user/shops_controller.rb
class User::ShopsController < ApplicationController

  def search
    if params[:keyword].present?
      # 住所もしくは店名で検索する
      @search_shops = Shop.where('address LIKE ? OR shop_name LIKE ?', "%#{params[:keyword]}%", "%#{params[:keyword]}%").page(params[:page]).per(20)
      @keyword = params[:keyword]

      # views/layouts/_side.html.erbに必要な記述
      @shops = Shop.all.order(created_at: :desc)
      @topics = Topic.all.order(created_at: :desc)
      @default_drinks = Drink.default.where(default_select: true)
    else
      redirect_to root_path    # 検索窓が空白の場合root_pathに遷移
    end
  end

  def index
    @shops = Shop.all.page(params[:page]).per(20)
  end

  def show
    @shop = Shop.find(params[:id])
    @breads = @shop.breads.all.order(created_at: :desc).page(params[:page]).per(30)
  end

  def onlines
    @shops = Shop.all.page(params[:page]).per(20)
  end
end

app/controllers/user/topics_controller.rb
class User::TopicsController < ApplicationController
  def index
    @topics = Topic.all.order(created_at: :desc).page(params[:page]).per(10)
  end

  def show
    @topic = Topic.find(params[:id])
  end
end

app/controllers/user/unlocks_controller.rb
# frozen_string_literal: true

class User::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/user/users_controller.rb
class User::UsersController < ApplicationController
  before_action :authenticate_user!, except: %i[index show]

  def index
    @users = User.active_users.all.page(params[:page]).per(20)
  end

  def show
    @user = User.find(params[:id])
    if @user.is_delete
      redirect_to users_path
      flash[:alert] = "そのユーザは削除されました。"
    else
      @breads = @user.breads.all.order(created_at: :desc).page(params[:page]).per(30)  #マイページの投稿一覧を新着順に
    end
  end

  def edit
    @user = current_user
  end

  def update
    @user = User.find(current_user.id)

    unless @user.update(user_params)
      render "user/users/error.js.erb"
    else
      redirect_to user_path(@user.id)
    end
  end

  def check
    @user = current_user
  end

  def withdraw    #退会処理(ステータスの更新)
    @user = current_user
    if params[:user][:agreement] == "1"
      @user.update(is_delete: true)
      reset_session
      flash[:notice] = "退会処理を実行いたしました"
      redirect_to root_path
    else
      flash.now[:alert] = "退会には「上記に同意する」へのチェックが必要です"
      @user = current_user
      render :check
    end
  end

  def destroy
  end


  private
  def user_params
    params.require(:user).permit(:name, :user_info, :user_image, :agreement)
  end

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/views/user/breads/_comment-form.html.erb
<!--vies/user/breads/show.html.erbから切り取り-->
      <%= form_with model:[@bread, @comment], local: false do |f| %>
        <span>
          <%= f.text_area :comment, placeholder:"コメントをどうぞ(*80文字以内)", rows: 1, class:"mt-4 form-control" %>
          <%= f.submit "送信する", class:"mt-2 btn btn-sm btn-outline-secondary" %>
        </span>
      <% end %>

app/views/user/breads/_comment-index.html.erb
<!--views/user/breads/show.html.erbから切り取り-->

<% bread.comments.each do |comment| %>
  <div class="my-2">
    <div class="row">
      <div class="ml-3">
        <%= image_tag comment.user.get_user_image(40, 40), class:"rounded-circle", as:"image" %>
      </div>
      <div class="col-7">
        <span class="small mr-1"><%= comment.user.name %></span>
        <span class="small text-secondary"><%= comment.created_at.strftime("%Y/%m/%d") %></span>
        <div><%= comment.comment %></div>
        <% if comment.user == current_user %>
          <span>
            <%= link_to "削除", bread_comment_path(bread.id, comment.id), method: :delete, remote: true, class:"small text-secondary" %>
          </span>
        <% end %>
      </div>
  　</div>
  </div>
<% end %>

app/views/user/breads/_post-form.html.erb
    <!--パンの投稿＆編集フォーム-->

    <div id="error">
      <%= render 'layouts/errors', obj: bread %>
    </div>

    <%= form_with model: bread, local: false do |f| %>
      <%= f.label :パン写真 %><br>
      <%= f.file_field :bread_image %><br>

      <!--<div class="form-group">-->
      <!--  <div class="custom-file">-->
      <!--    <%#= f.file_field :bread_image, class: "custom-file-input", id: "customFile" %>-->
      <!--    <label class="custom-file-label" for="customFile">ファイルを選択</label>-->
      <!--  </div>-->
      <!--</div>-->

      <%= f.label :パン名, class:"mt-4" %>
      <%= f.text_field :bread_name, class:'form-control', placeholder: "*20文字以内" %>

      <%= f.radio_button :taste, :true %>
      <%= f.label :甘い系 %>
      <%= f.radio_button :taste, :false, class:"ml-3" %>
      <%= f.label :塩味系 %><br>

      <%= f.label :紹介, class:"mt-2" %>
      <%= f.text_area :introduce, rows: 3, class:"form-control", style:"resize: none;", placeholder: "味や感想を教えて！(*150文字以内)" %>

      <%= f.label :一緒に飲むなら？, class:"mt-4" %><br>
      <!--seed.rbで設定済みのデフォルトドリンク4種-->
      <% Drink.default.each do |drink| %>
        <span class="mr-4">
          <% case drink.drink_name
          when "コーヒー" %>
            <%= f.radio_button :drink_name, drink.id, checked: true %> #
          <% when "紅茶" %>
            <%= f.radio_button :drink_name, drink.id %> #
          <% when "牛乳" %>
            <%= f.radio_button :drink_name, drink.id %> #
          <% when "お茶" %>
            <%= f.radio_button :drink_name, drink.id %> #
          <% end %>
          <%= f.label :drink_name, drink.drink_name %>
        </span>
      <% end %>

      <div class="mt-1">
        <%= f.radio_button :drink_name, "other" %>
        <%= f.label :drink_name, "#その他" %>
        <%= f.select :other_drink_name, options_from_collection_for_select(Drink.not_default, :id, :drink_name) %>
      <!--other_drink_nameのはnot_default、つまりadminでdrink_name登録式を採用している方-->
      </div>

      <%= f.label :ショップ選択, class:"mt-4" %>
      <%= f.select :shop_id, options_from_collection_for_select(Shop.all, :id, :address_display), { include_blank: true }, class:"select_search", style:"width: 100%"%>   <!--addressメソッドはshop.rbで定義-->
      <%= f.submit class:"mt-4 btn btn-secondary" %>
    <% end %>

app/views/user/breads/edit.html.erb
<div class="main-theme container py-5">
  <div class="col-md-6 mx-auto">

    <h5 class="mb-4">パンの編集</h5>
    <%= render 'post-form', bread: @bread %>

  </div>
</div>

app/views/user/breads/error.js.erb
if($('#error').length){
  $('#error').html("<%= j(render 'layouts/errors', obj: @bread) %>");
}

app/views/user/breads/index.html.erb
<div class="main-theme container pt-5">
  <div class="mx-auto">
    <h5 class="mb-4 ml-2"><%= @drink.drink_name %>におすすめのパン</h5>

    <div class="row">
      <div class="col-md-12">
        <ul class="row ml-3">
          <% @breads.each do |bread| %>
            <li class="mr-1 sentence" style="max-width: 150px;">
              <div>
                <%= link_to bread_path(bread.id), class:"text-dark" do %>
                  <%= image_tag bread.get_bread_image(150, 150) %><br>
                  <%= bread.bread_name %>
                <% end %>
              </div>
            </li>
          <% end %>
        </ul>
      </div>

    </div>

    <div class="d-flex justify-content-center pt-3">
      <%= paginate @breads, theme: 'twitter-bootstrap-4' %>
    </div>

  </div>
</div>

app/views/user/breads/new.html.erb
<div class="main-theme container mx-auto py-5">
  <div class="col-md-8 mx-auto">

    <h5 class="mb-4">投稿フォーム</h5>
    <%= render 'post-form', bread: @bread %>

  </div>
</div>

app/views/user/breads/search.html.erb
<!--パンの検索結果を表示する-->
<div class="container pt-5">
  <div class="mx-auto">
    <div class="row">

      <div class="col-9">
        <h5 class="mb-4">"<%= @keyword %>" の検索結果 <%= @search_breads.count %>件</h5>
        <% if @keyword.present? %>
          <ul class="row ml-2" style="list-style: none;">
            <% @search_breads.each do |bread| %>
              <li class="mr-1">
                <div>
                  <%= link_to bread_path(bread.id) do %>
                    <%= image_tag bread.get_bread_image(180, 180) %><br>
                  <% end %>
                  <%= bread.bread_name %>
                </div>
              </li>
            <% end %>
          </ul>
        <% end %>
      </div>

    </div>

    <div class="d-flex justify-content-center pt-3">
      <%= paginate @search_breads, theme: 'twitter-bootstrap-4' %>
    </div>

  </div>
</div>

app/views/user/breads/show.html.erb
<div class="main-theme container py-5">

  <% if @user != current_user %>  <!--他ユーザの投稿詳細ページならユーザリンクを表示-->
    <div class="row mb-3">
      <div class="col-md-9">
        <%= link_to user_path(@user.id) do %>
          <%= image_tag @user.get_user_image(80, 80), class:"rounded-circle" %>
          <span class="text-dark ml-2"><%= @user.name %></span>
        <% end %>
      </div>
    </div>
  <% end %>

  <div class="row">
    <div class="col-md-5">
      <%= image_tag @bread.get_bread_image(400, 400), class:"mb-3 resize-image" %>
    </div>

    <div class="col-md-7">
      <h5><%= @bread.bread_name %></h5>
      <p style="height: 160px;"><%= @bread.introduce %></p>

      <dl class="row">
        <dd class="col-sm-7">ジャンル：
          <% if @bread.taste %>    <!--trueは甘、falseは塩-->
            甘い系
          <% else %>
            塩味系
          <% end %>
        </dd>

        <dd class="col-sm-7">パンのお供：
          # <%= @bread.drink.drink_name %>
        </dd>

        <dd class="col-sm-7">購入店：
          <% if @bread.shop %>
            <%= link_to shop_path(@bread.shop) do %><br>
              <span class="text-dark">〒<%= @bread.shop.postcode %>　<%= @bread.shop.address %></span><br>
              <span class="text-dark"><%= @bread.shop.shop_name %></span>
            <% end %>
          <% end %>
        </dd>

        <dd class="col-sm-9">投稿日：
          <%= @bread.created_at.strftime("%Y/%m/%d") %>
          <% if @bread.updated_at - @bread.created_at > 5.minutes %>
            <span class="py-2 text-secondary"><small>(最終更新 <%= @bread.updated_at.in_time_zone('Tokyo').strftime("%Y/%m/%d %H:%M") %>)</small></span>    <!--東京時間のhour/minutesまで表示-->
          <% end %>
        </dd>
      </dl>


      <!--いいね機能非同期化→favorites/_favorite-btn.html.erb-->
      <span id="favorite-btn_<%= @bread.id %>">
        <%= render 'user/favorites/favorite-btn', bread: @bread %>
      </span>

      <span class="ml-3"><i class="far fa-comment-dots fa-flip-horizontal"></i> <%= @bread.comments.count %></span>


      <% if @bread.user == current_user %>
        <%= link_to "編集", edit_bread_path(@bread.id), class:"ml-5 btn btn-outline-secondary" %>
        <%= link_to "削除", bread_path(@bread.id), method: :delete, "data-confirm" => "本当に削除しますか？", class:"btn btn-outline-secondary" %>
      <% end %>
    </div>
  </div>


  <div class="row">
    <div class="col-md-8">
      <!--コメント一覧非同期化-->
        <div id="comment-index" class="mt-3">
          <%= render 'user/breads/comment-index', bread: @bread  %>
        </div>

      <!--コメントフォーム非同期化-->
      <div id="comment-form">
        <%= render 'user/breads/comment-form', bread: @bread, comment: @comment %>
      </div>

    </div>
  </div>


</div>