config/routes.rb
Rails.application.routes.draw do

  # 顧客用
  # URL /customers/sign_in ...
  devise_for :user, controllers: {
    registrations: "user/registrations",
    sessions: 'user/sessions'
  }

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, controllers: {
    sessions: "admin/sessions",
  }

  # ゲストログイン用
  # post '/homes/guest_sign_in' => 'homes#guest_sign_in'
  devise_scope :user do
    post 'user/guest_sign_in' => 'user/sessions#guest_sign_in'
  end

  root to: 'user/homes#top'

  scope module: :user do
    get 'homes/about'
    get 'feedbacks/thanks'
    resources:feedbacks, only: [:new, :create]
    get 'users/mypage/edit' => 'users#edit'
    patch 'users/mypage/edit' => 'users#update'
    get 'users/check'
    patch 'users/withdraw'
    resources:users, only: [:index, :show, :edit, :destroy]

    resources:breads, only: [:index, :new, :create, :show, :edit, :update, :destroy] do
      resources:comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
      collection do
        get 'search'
      end
    end

    get 'favorites/index'

    resources:topics, only: [:index, :show]
    get 'shops/onlines'

    resources:shops, only: [:index, :show] do
      collection do
        get 'search'
      end
    end

    get 'drinks/index'
  end

  namespace :admin do
    root to: 'homes#top'
    resources:users, only: [:index, :show, :edit, :update, :destroy]

    resources:breads, only: [:index, :show, :destroy] do
      resources:comments, only: [:create, :destroy]
      collection do
        get 'search'
      end
    end

    resources:topics, only: [:index, :new, :create, :show, :edit, :update, :destroy]
    resources:shops, only: [:index, :new, :create, :show, :edit, :update, :destroy]
    resources:drinks, only: [:index, :new, :create, :edit, :update, :destroy]
    get 'feedbacks/solved'    # 解決済みご意見のindex
    resources:feedbacks, only: [:index, :show, :update, :destroy]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/bread.rb
class Bread < ApplicationRecord

  scope :active_users_breads, -> { includes(:user).where(user: { is_delete: false }) }


  belongs_to :user
  belongs_to :shop, optional: true    # shopのnilを許す
  has_many :topic

  belongs_to :drink
  accepts_nested_attributes_for :drink

  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorited_users, through: :favorites, source: :user    #いいね順

  def favorite_by?(user)
    user.present? && favorites.exists?(user_id: user.id)
  end


  validates :bread_image, presence: true
  validates :bread_name, presence: true, length:{maximum:20}
  validates :introduce, presence: true, length:{maximum:150}
  validates :taste, inclusion: {in: [true, false], message: 'はどちらかを選択してください' }

  has_one_attached :bread_image

  def get_bread_image(width, height)
    unless bread_image.attached?
      file_path = Rails.root.join('app/assets/images/no-bread-image.jpg')
      bread_image.attach(io: File.open(file_path), filename: "default-image.jpg", content_type: "image/jpeg")
    end
    bread_image.variant(resize_to_fill: [width, height]).processed   #写真をresize_to_fillでスクエアに
  end


end

app/controllers/admin/breads_controller.rb
class Admin::BreadsController < ApplicationController
  before_action :authenticate_admin!

  def search
    if params[:keyword].present?
      @search_breads = Bread.active_users_breads.where('bread_name LIKE ?', "%#{params[:keyword]}%").page(params[:page]).per(100)
      @keyword = params[:keyword]
      @shops = Shop.all.order(created_at: :desc)
    else
      redirect_to root_path    # 検索窓が空白の場合root_pathに遷移
    end
  end


  def index
    @breads = Bread.active_users_breads.all.order(updated_at: :desc).page(params[:page]).per(100)
  end

  def show
    @bread = Bread.find(params[:id])
    @user = @bread.user
  end

  def destroy
    bread = Bread.find(params[:id])
    user_id = bread.user.id

    bread.destroy
    redirect_to admin_user_path(user_id)

  end
end

app/controllers/user/breads_controller.rb
class User::BreadsController < ApplicationController
  before_action :authenticate_user!, except: %i[search index show]

  def search
    if params[:keyword].present?
      @search_breads = Bread.active_users_breads.where('bread_name LIKE ?', "%#{params[:keyword]}%").page(params[:page]).per(20)
      @keyword = params[:keyword]
    else
      redirect_to root_path    # 検索窓が空白の場合root_pathに遷移
    end
  end

  def index
    return redirect_to root_path unless params[:drink_id]    # breads/new再リロード時のエラー回避
    @drink = Drink.find_by(id: params[:drink_id])
    @breads = @drink.breads.active_users_breads.order(created_at: :desc).page(params[:page]).per(20)
  end

  def show
    # 例外処理、削除された投稿はアクセス不可
    begin
      @bread = Bread.find(params[:id])
      @user = @bread.user
      @comment = Comment.new
    rescue ActiveRecord::RecordNotFound
      redirect_to root_path
    end
  end

  def new
    @bread = Bread.new
  end

  def create
    @bread = Bread.new(bread_params)
    @bread.user_id = current_user.id

    if params[:bread][:drink_name] == "other"
      drink_id = params[:bread][:other_drink_name]
    else
      drink_id = params[:bread][:drink_name]
    end

    drink = Drink.find_by(id: drink_id)
    @bread.drink_id = drink.id

    unless @bread.save
      render "user/breads/error.js.erb"
    else
      redirect_to bread_path(@bread.id)
    end
  end

  def edit
    @bread = Bread.find(params[:id])
  end

  def update
    @bread = Bread.find(params[:id])

    if params[:bread][:drink_name] == "other"
      drink_id = params[:bread][:other_drink_name]
    else
      drink_id = params[:bread][:drink_name]
    end

    drink = Drink.find(drink_id)

    @bread.drink = drink

    unless @bread.update(bread_params)
      render 'user/breads/error.js.erb'
    else
      flash[:notice] = "投稿を編集しました"
      redirect_to bread_path
    end
  end

  def destroy
    bread = Bread.find(params[:id])
    bread.destroy
    redirect_to user_path(current_user)
  end


  private
  def bread_params
    params.require(:bread).permit(:bread_name, :introduce, :taste, :bread_image, :shop_id, drink_attributes: [:drink_name, :other_drink_name])
  end


end

app/helpers/admin/breads_helper.rb
module Admin::BreadsHelper
end

app/helpers/user/breads_helper.rb
module User::BreadsHelper
end

app/views/admin/breads/destroy.html.erb
<h1>Admin::Breads#destroy</h1>
<p>Find me in app/views/admin/breads/destroy.html.erb</p>

app/views/admin/breads/index.html.erb
<div class="main-theme container py-5">

  <div class="row">
    <h5 class="ml-4">新着投稿一覧(更新順)</h5>
  </div>
  <div>
    <ul class="row col-md-12 mx-auto">
      <% @breads.each do |bread| %>
        <li class="mr-1 mb-1 sentence" style="max-width: 100px;">
          <%= link_to admin_bread_path(bread.id) do %>
            <div><%= image_tag bread.get_bread_image(100, 100) %></div>
            <p class="text-dark">
              <%= bread.bread_name %><br>
              <span><small><%= bread.updated_at.strftime('%Y/%m/%d') %></small></span>    <!--最終更新日-->
            </p>
          <% end %>
        </li>
      <% end %>
    </ul>
  </div>

  <div class="d-flex justify-content-center pb-3">
    <%= paginate @breads, theme: 'twitter-bootstrap-4' %>
  </div>

</div>

app/views/admin/breads/search.html.erb
<div class="main-theme container py-5">

    <div class="row">
      <div class="col-md-12">
        <h5 class="mb-4">"<%= @keyword %>" の検索結果 <%= @search_breads.count %>件</h5>
        <% if @keyword.present? %>
          <div>
            <ul class="row ml-2">
              <% @search_breads.each do |bread| %>
                <li class="mr-1 sentence" style="max-width: 100px;">
                  <div>
                    <%= link_to admin_bread_path(bread.id) do %>
                      <%= image_tag bread.get_bread_image(100, 100) %><br>
                    <% end %>
                    <%= bread.bread_name %>
                  </div>
                </li>
              <% end %>
            </ul>
          </div>
        <% end %>
      </div>
    </div>

    <div class="d-flex justify-content-center pb-3">
      <%= paginate @search_breads, theme: 'twitter-bootstrap-4' %>
    </div>

</div>

app/views/admin/breads/show.html.erb
<div class="main-theme container py-5">

 <div class="row">
    <div class="col-md-5">
      <%= image_tag @bread.get_bread_image(400, 400), class:"mb-3 resize-image" %>
    </div>

    <div class="col-md-7">
      <h5><%= @bread.bread_name %></h5>
      <p style="height: 160px;"><%= @bread.introduce %></p>

      <dl class="row">
        <dd class="col-sm-7">ジャンル：
          <% if @bread.taste %>    <!--trueは甘、falseは塩-->
            甘い系
          <% else %>
            塩味系
          <% end %>
        </dd>

        <dd class="col-sm-7">パンのお供：
          # <%= @bread.drink.drink_name %>
        </dd>

        <dd class="col-sm-7">購入店：
          <% if @bread.shop %>
            <%= link_to admin_shop_path(@bread.shop) do %><br>
              <span class="text-dark">〒<%= @bread.shop.postcode %>　<%= @bread.shop.address %></span><br>
              <span class="text-dark"><%= @bread.shop.shop_name %></span>
            <% end %>
          <% end %>
        </dd>

        <dd class="col-sm-9">投稿日：
          <%= @bread.created_at.strftime("%Y/%m/%d") %>
          <% if @bread.updated_at - @bread.created_at > 5.minutes %>
            <span class="py-2 text-secondary"><small>(最終更新 <%= @bread.updated_at.in_time_zone('Tokyo').strftime("%Y/%m/%d %H:%M") %>)</small></span>    <!--東京時間のhour/minutesまで表示-->
          <% end %>
        </dd>
      </dl>


      <% if @bread.favorite_by?(current_user) %>
        <span class="mt-3">
          <i class="fas fa-heart" style="color: #e40101;"></i> <%= @bread.favorites.count %>
        </span>
      <% else %>
        <span class="mt-3">
          <i class="far fa-heart" style="color: #e40101;"></i> <%= @bread.favorites.count %>
        </span>
      <% end %>

      <span class="ml-3"><i class="far fa-comment-dots fa-flip-horizontal"></i> <%= @bread.comments.count %></span>

      <div><%= link_to "ユーザー詳細", admin_user_path(@user.id), class:"mt-3 btn btn-sm btn-warning" %></div>
      <%= link_to admin_bread_path(@bread.id), method: :delete, "data-confirm" => "本当に削除しますか？", class:"mt-3 btn btn-sm btn-danger" do %>
        <div><%= @user.name %>さんのこの投稿を削除する</div>
      <% end %>
    </div>

    <div class="row ml-4 mt-3">
      <div>
        <% if @bread.comments.exists? %>
          <% @bread.comments.each do |comment| %>
            <div class="my-2">
              <div class="row">
                <div class="ml-1">
                  <%= image_tag comment.user.get_user_image(40, 40), class:"rounded-circle" %>
                </div>
                <div class="col-7">
                  <span class="small mr-1"><%= comment.user.name %></span>
                  <span class="small text-secondary"><%= comment.created_at.strftime("%Y/%m/%d") %></span>
                  <div><%= comment.comment %></div>
                  <span>
                    <%= link_to "削除", admin_bread_comment_path(comment.bread_id, comment.id), method: :delete, "data-confirm" => "コメントを削除します", style:"font-size: 8px; color: gray;" %>
                  </span>
                </div>
              </div>
            </div>
          <% end %>
        <% else %>
          <div>コメントはありません</div>
        <% end %>
      </div>
    </div>

  </div>
</div>